ccflags-y += -Idrivers/media/platform/msm/camera_v2_amz
ccflags-y += -Idrivers/media/platform/msm/camera_v2_amz/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_amz/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2_amz/sensor/ois
obj-$(CONFIG_BU63164) += bu63164.o
