ccflags-y += -Idrivers/media/platform/msm/camera_v2_amz
ccflags-y += -Idrivers/media/platform/msm/camera_v2_amz/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_amz/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
