ccflags-y += -Idrivers/media/platform/msm/camera_v2_amz
ccflags-y += -Idrivers/media/platform/msm/camera_v2_amz/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_amz/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
