ccflags-y += -Idrivers/media/platform/msm/camera_v2_amz
ccflags-y += -Idrivers/media/platform/msm/camera_v2_amz/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_amz/sensor/cci
obj-$(CONFIG_BU63164) += bu63164/
obj-$(CONFIG_MSM_OIS) += msm_ois.o
