ccflags-y += -Idrivers/media/platform/msm/camera_v2_amz
ccflags-y += -Idrivers/media/platform/msm/camera_v2_amz/sensor/io
obj-$(CONFIG_MSM_CSID) += msm_ispif.o
obj-$(CONFIG_MSM_CSID) += msm_ispif_debugfs.o
obj-$(CONFIG_MSM_CSID) += msm_ispif_frame_event.o
